### ISSUE TITLE
distance() always 0 ?

### ISSUE THREAD

**Issue by ZoomQuiet** [liangsun/simhash#14]
problems is :

- the different string
- always same Simhash ...

thanx for all suggest

example code as:

    print as_target
    sh1 = Simhash(as_target)
    print '%x' % Simhash(get_features(as_target)).value
    print id(sh1)

    print as_user
    sh2 = Simhash(as_user)
    print '%x' % Simhash(get_features(as_user)).value
    print id(sh2)

    print sh1.distance(sh2)

the stdout like:

    0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
    415435ffb1fa93d4
    4367884816
    0000001000000010001100001100010010000000000000000000000010000010000000100000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
    415435ffb1fa93d4
    4367884944
    0

**Comment by liangsun** [comment]
I look into your test, the features for `as_target` is
```
{u'0000': 286}
```
while the features for `as_user` is

```
{u'0110': 2, u'0000': 244, u'0001': 10, u'0011': 2, u'0010': 8, u'0100': 8, u'1100': 2, u'1001': 1, u'1000': 9}
```

For both two features, the feature `0000` dominants the whole features. (The weight for `0000` is too high so that all other features can be ignored)

I don't know what's your code for, but you may parse in customized feature list. For example,

```
def get_features(s):
    return list(set(_tokenize(s)))
```

Or you may use other algorithms to check the differences between these two strings, for example the editing distance algorithm in O(n^2).

**Comment by ZoomQuiet** [comment]
thanx for suggest ;-)
